export const gitmojis = [
  {
    emoji: "🎉",
    entity: "&#127881;",
    code: ":tada:",
    description: "Begin a project.",
    name: "feat",
    semver: null,
  },
  {
    emoji: "✨",
    entity: "&#x2728;",
    code: ":feat:",
    description: "A new feature.",
    name: "feat",
    semver: "minor",
  },
  {
    emoji: "🚧",
    entity: "&#x1f6a7;",
    code: ":construction:",
    description: "Work in progress.",
    name: "feat",
    semver: null,
  },
  {
    emoji: "🐛",
    entity: "&#x1f41b;",
    code: ":fix:",
    description: "Fix a bug.",
    name: "fix",
    semver: "patch",
  },
  {
    emoji: "🚑️",
    entity: "&#128657;",
    code: ":ambulance:",
    description: "Critical hotfix.",
    name: "fix",
    semver: "patch",
  },
  {
    emoji: "💄",
    entity: "&#ff99cc;",
    code: ":style:",
    description: "Add or update the UI and style files.",
    name: "style",
    semver: "patch",
  },
  {
    emoji: "🎨",
    entity: "&#x1f3a8;",
    code: ":art:",
    description: "Improve structure / format of the code.",
    name: "art",
    semver: null,
  },
  {
    emoji: "♻️",
    entity: "&#x267b;",
    code: ":refactor:",
    description: "A code change that neither fixes a bug nor adds a feature.",
    name: "refactor",
    semver: null,
  },
  {
    emoji: "⚡️",
    entity: "&#x26a1;",
    code: ":perf:",
    description: "Improve performance.",
    name: "perf",
    semver: "patch",
  },
  {
    emoji: "📝",
    entity: "&#x1f4dd;",
    code: ":docs:",
    description: "Add or update documentation.",
    name: "docs",
    semver: null,
  },
  {
    emoji: "🔥",
    entity: "&#x1f525;",
    code: ":remove:",
    description: "Remove code or files.",
    name: "remove",
    semver: null,
  },
  {
    emoji: "✅",
    entity: "&#x2705;",
    code: ":white_check_mark:",
    description: "Add, update, or pass tests.",
    name: "test",
    semver: null,
  },
  {
    emoji: "🧪",
    entity: "&#x1F9EA;",
    code: ":test_tube:",
    description: "Add a failing test.",
    name: "test",
    semver: null,
  },
  {
    emoji: "⬇️",
    entity: "⬇️",
    code: ":arrow-down:",
    description: "Downgrade dependencies.",
    name: "feat",
    semver: "patch",
  },
  {
    emoji: "⬆️",
    entity: "⬆️",
    code: ":arrow_up:",
    description: "Upgrade dependencies.",
    name: "feat",
    semver: "patch",
  },
  {
    emoji: "📈",
    entity: "&#x1F4C8;",
    code: ":chart_with_upwards_trend:",
    description: "Add or update analytics or track code.",
    name: "feat",
    semver: "patch",
  },
  {
    emoji: "➕",
    entity: "&#10133;",
    code: ":heavy_plus_sign:",
    description: "Add a dependency.",
    name: "feat",
    semver: "patch",
  },
  {
    emoji: "➖",
    entity: "&#10134;",
    code: ":heavy_minus_sign:",
    description: "Remove a dependency.",
    name: "feat",
    semver: "patch",
  },
  {
    emoji: "🔧",
    entity: "&#x1f527;",
    code: ":wrench:",
    description: "Add or update configuration files.",
    name: "feat",
    semver: "patch",
  },
  {
    emoji: "🔨",
    entity: "&#128296;",
    code: ":hammer:",
    description: "Add or update development scripts.",
    name: "feat",
    semver: null,
  },
  {
    emoji: "💩",
    entity: "&#58613;",
    code: ":poop:",
    description: "Write bad code that needs to be improved.",
    name: "feat",
    semver: null,
  },
  {
    emoji: "🔀",
    entity: "&#128256;",
    code: ":twisted_rightwards_arrows:",
    description: "Merge branches.",
    name: "feat",
    semver: null,
  },
  {
    emoji: "🔍️",
    entity: "&#128269;",
    code: ":mag:",
    description: "Improve SEO.",
    name: "feat",
    semver: "patch",
  },
  {
    emoji: "🏷️",
    entity: "&#127991;",
    code: ":label:",
    description: "Add or update types.",
    name: "feat",
    semver: "patch",
  },
];
